ALTER TABLE estates ENABLE ROW LEVEL SECURITY;
ALTER TABLE estate_managers ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE managers ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_verification_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE configuration_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;